---
- name: GIT | Include distribution specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml
      paths:
        - vars
  tags:
    - git

- name: GIT | Ensure git's dependencies are installed.
  ansible.builtin.package:
    name: "{{ git_install_from_source_dependencies }}"
    state: present

- name: GIT | Get installed version.
  debug:
    msg: "GIT NOT found"
  when: "'git' not in ansible_facts.packages"
  register: git_installed

- name: GIT | Remove the GIT package and upgrade
  ansible.builtin.package:
    name: git
    state: absent
  when: "'git' in ansible_facts.packages"

- name: GIT | Force git install if the version numbers do not match.
  ansible.builtin.set_fact:
    git_reinstall_from_source: true
  when:
    - git_install_from_source_force_update | bool
    - ("'git' not in ansible_facts.packages")

- name: GIT | Download git from source
  ansible.builtin.get_url:
    url: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
    dest: "{{ workspace }}/git-{{ git_version }}.tar.gz"
  when:
    - (git_reinstall_from_source | bool) or (ansible_facts.packages.git[0].version < git_version)

- name: GIT | Expand git archive.
  ansible.builtin.unarchive:
    src: "{{ workspace }}/git-{{ git_version }}.tar.gz"
    dest: "{{ workspace }}"
    creates: "{{ workspace }}/git-{{ git_version }}/README"
    copy: false
  when:
    - (git_reinstall_from_source | bool) or (ansible_facts.packages.git[0].version < git_version)

- name: GIT | Build git from source
  community.general.make:
    chdir: "{{ workspace }}/git-{{ git_version }}"
    target: "{{ item }}"
    params:
      prefix: "{{ git_install_path }}"
  loop:
    - all
    - install
  when:
    - (git_reinstall_from_source | bool) or (ansible_facts.packages.git[0].version < git_version)
  become: true

- name: GIT | Remove file (delete file) after install
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ workspace }}/git-{{ git_version }}.tar.gz"
    - "{{ workspace }}/git-{{ git_version }}"
