---
- name: GIT | Include distribution specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml
      paths:
        - vars
  tags:
    - git

- name: GIT | Get installed version.
  ansible.builtin.shell: >
    which git && git --version | grep -o '\([0-9\.]*\)'
  failed_when: false
  check_mode: false
  register: git_version_ok
  changed_when: (git_version_ok.rc != 0) or (git_version_ok.stdout_lines[1] is version(git_version, '<'))

- name: GIT | Remove the GIT current package and upgrade
  ansible.builtin.package:
    name: git
    state: absent
  become: true
  when: (git_version_ok.rc != 0) or (git_version_ok.stdout_lines[1] is undefined) or (git_version_ok.stdout_lines[1] is version(git_version, '<'))

- name: GIT | Ensure git's dependencies are installed.
  ansible.builtin.package:
    name: "{{ git_install_from_source_dependencies }}"
    state: present
  when: git_version_ok.changed | bool

- name: GIT | Force git install if the version numbers do not match.
  ansible.builtin.set_fact:
    git_reinstall_from_source: true
  when:
    - git_install_from_source_force_update | bool
    - git_version_ok.changed | bool

- name: GIT | Build temp directory
  ansible.builtin.file:
    path: "{{ workspace }}"
    state: directory

- name: GIT | Download git from source
  ansible.builtin.get_url:
    url: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
    dest: "{{ workspace }}/git-{{ git_version }}.tar.gz"
  when: (git_version_ok.changed | bool) or (git_reinstall_from_source | bool)

- name: GIT | Expand git archive.
  ansible.builtin.unarchive:
    src: "{{ workspace }}/git-{{ git_version }}.tar.gz"
    dest: "{{ workspace }}"
    creates: "{{ workspace }}/git-{{ git_version }}/README"
    copy: false
  when: (git_version_ok.changed | bool) or (git_reinstall_from_source | bool)

- name: GIT | Build git from source
  ansible.builtin.command: >
    make prefix={{ git_install_path }} {{ item }}
    chdir={{ workspace }}/git-{{ git_version }}
  loop:
    - all
    - install
  when: (git_version_ok.rc != 0) or (git_reinstall_from_source | bool)
  become: true
  register: git_installed

- name: Check if the directory exists
  ansible.builtin.stat:
    path: "{{ workspace }}"
  register: dir_to_check

- name: GIT | Cleanup install (delete files)
  ansible.builtin.command: >
    rm -rf {{ workspace }}
  ignore_errors: true
  become: true
  when: (git_installed.changed | bool and not git_installed.failed | bool) or (dir_to_check.stat.isdir is defined and dir_to_check.stat.isdir)
