---
- name: Validate role variables
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate/validate.yml"
  tags: git_validate

- name: Check if Git installed version
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/ensure-version.yml"
  tags: git_check

- name: Remove/Upgrade Git installed version
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/remove-package.yml"
  tags: git_upgrade_config

- name: Install dependencies
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/prerequisites/install-dependencies.yml"
  tags: git_prerequisites

- name: Install Git package
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/install/install-package.yml"
  tags: git_install

- name: Install Git package from source
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/install/install-source-package.yml"
  tags: git_install_source
