---
- name: GIT | Ensure git is installed (RedHat).
  ansible.builtin.package:
    name: "{{ git_packages }}"
    state: present
  when:
    - not git_install_from_source | bool
    - ansible_facts['os_family'] == 'RedHat'

- name: GIT | Add git repository from ppa (Debian).
  ansible.builtin.apt_repository:
    repo: "{{ git_repository }}"
    state: present
  when:
    - not git_install_from_source | bool
    - ansible_facts['os_family'] == 'Debian'

- name: GIT | Update apt cache (Debian).
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when:
    - not git_install_from_source | bool
    - ansible_facts['os_family'] == 'Debian'

- name: GIT | Ensure git is installed (Debian).
  ansible.builtin.apt:
    name: "{{ git_packages }}"
    state: latest
  when:
    - not git_install_from_source | bool
    - ansible_facts['os_family'] == 'Debian'

- import_tasks: install-from-source.yml
  when: git_install_from_source | bool
