---
- name: Converge
  hosts: all
  become: true

  vars:
    git_install_from_source: true
    git_reinstall_from_source: true
    git_version: "2.40.1"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: "asapdotid.git"
